spring:
  application:
    name: neaterp-server

  profiles:
    active: local

  main:
    allow-circular-references: true  # 允许循环依赖，因为项目是三层架构，无法避免这个情况。




--- #################### neaterp相关配置 ####################

neaterp:
  info:
    version: 1.0.0
    base-package: com.neaterp
  xss:
    enable: false
  web:
    admin-ui:
      url: https://www.baidu.com